import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { join } from 'node:path';
import kleur from 'kleur';
import prompts from 'prompts';
import { type LocalSkill, scanAll } from '../scan.js';

const CONFIG_DIR = join(homedir(), '.skillpulse');
const CONFIG_PATH = join(CONFIG_DIR, 'config.json');

interface Config {
  userId: string;
  consentedAt?: string;
  autoShare?: boolean;
  lastShare?: string;
}

async function loadConfig(): Promise<Config | null> {
  if (!existsSync(CONFIG_PATH)) return null;
  try {
    return JSON.parse(await readFile(CONFIG_PATH, 'utf-8')) as Config;
  } catch {
    return null;
  }
}

async function saveConfig(config: Config): Promise<void> {
  await mkdir(CONFIG_DIR, { recursive: true });
  await writeFile(CONFIG_PATH, JSON.stringify(config, null, 2));
}

function anonymousId(): string {
  return createHash('sha256')
    .update(homedir() + process.platform + Date.now())
    .digest('hex')
    .slice(0, 16);
}

export async function share(opts: { silent?: boolean } = {}): Promise<void> {
  const silent = opts.silent ?? false;

  let config = await loadConfig();

  // First-run consent flow
  if (!config?.consentedAt && !silent) {
    console.log(kleur.bold().yellow('\n  SkillPulse — Community Registry\n'));
    console.log('  SkillPulse grows when users share what they use locally.');
    console.log('  Your contribution helps everyone discover the best tools.\n');
    console.log(kleur.dim('  What gets shared (anonymously):'));
    console.log(kleur.dim('    • Names of MCPs and skills you have configured'));
    console.log(kleur.dim('    • Public URLs (from settings.json mcpServers)'));
    console.log(kleur.dim('  What is NEVER shared:'));
    console.log(kleur.dim('    • Your API keys, tokens, or credentials'));
    console.log(kleur.dim('    • File contents or personal data'));
    console.log(kleur.dim('    • Your identity (anonymous hash only)\n'));

    const response = await prompts([
      {
        type: 'confirm',
        name: 'consent',
        message: 'Contribute anonymously to the SkillPulse registry?',
        initial: true,
      },
      {
        type: (prev) => (prev ? 'confirm' : null),
        name: 'autoShare',
        message: 'Auto-share when Claude Code starts? (recommended)',
        initial: true,
      },
    ]);

    if (!response.consent) {
      console.log(kleur.dim('\n  No problem — you can run `skillpulse share` anytime.\n'));
      return;
    }

    config = {
      userId: anonymousId(),
      consentedAt: new Date().toISOString(),
      autoShare: response.autoShare,
    };
    await saveConfig(config);
  } else if (!config) {
    // silent mode without consent = no-op
    return;
  }

  const skills = await scanAll();
  if (skills.length === 0) {
    if (!silent) console.log(kleur.dim('  No local MCPs or skills detected. Nothing to share.'));
    return;
  }

  // Throttle: only share once per 24h in auto mode
  if (silent && config.lastShare) {
    const ageMs = Date.now() - new Date(config.lastShare).getTime();
    if (ageMs < 24 * 60 * 60 * 1000) return;
  }

  const payload = {
    userId: config.userId,
    timestamp: new Date().toISOString(),
    platform: process.platform,
    skills: skills.map((s) => ({
      name: s.name,
      kind: s.kind,
      ...(s.url ? { url: s.url } : {}),
      ...(s.description ? { description: s.description.slice(0, 200) } : {}),
    })),
  };

  // Submit via GitHub issue (anonymous; maintainer bot picks it up)
  try {
    const issueTitle = `[TELEMETRY] Share from ${config.userId} — ${skills.length} items`;
    const issueBody = `<!-- autogenerated by @skillpulse/cli v1.1.0 -->

\`\`\`json
${JSON.stringify(payload, null, 2)}
\`\`\`

<sub>Anonymous contribution. User hash only, no personal data.</sub>`;

    // Use public GitHub "submit issue" URL (no auth required to open a preview)
    const ghUrl = new URL('https://github.com/corazzione/skillpulse/issues/new');
    ghUrl.searchParams.set('title', issueTitle);
    ghUrl.searchParams.set('body', issueBody);
    ghUrl.searchParams.set('labels', 'telemetry:anonymous');

    if (silent) {
      // In silent (hook) mode, just write to local queue for the user to review later
      const queueDir = join(CONFIG_DIR, 'queue');
      await mkdir(queueDir, { recursive: true });
      await writeFile(join(queueDir, `${Date.now()}.json`), JSON.stringify(payload, null, 2));
    } else {
      console.log(kleur.green(`\n  ✓ Found ${skills.length} local items:`));
      for (const s of skills) {
        console.log(kleur.dim(`    ${kindEmoji(s.kind)} ${s.name}`));
      }
      console.log();
      console.log(kleur.bold('  Open this link to submit (no login needed to preview):'));
      console.log(kleur.cyan(`  ${ghUrl.toString()}`));
      console.log();
    }

    config.lastShare = new Date().toISOString();
    await saveConfig(config);
  } catch (err) {
    if (!silent) console.error(kleur.red('  ✗ Failed to share:'), String(err));
  }
}

function kindEmoji(kind: LocalSkill['kind']): string {
  return { skill: '🧠', 'mcp-server': '🔌', plugin: '🧩' }[kind];
}
